### ISSUE TITLE
Search fails

### ISSUE THREAD

**Issue by IOIO72** [lxbrvr/alfred-keepassxc-workflow#1]
I've set up the workflow with a kp database, which is protected by a master password.
Unfortunately the debug output shows the following for any search.

```
KeepassXC Alfred[Script Filter] Queuing argument 'test'
KeepassXC Alfred[Script Filter] Script with argv 'test' finished
KeepassXC Alfred[Script Filter] {"items": [{"valid": false, "title": "There aren't matches or something went wrong."}]}
```

I've attached a test database, which is protected by the master password `test`
[test.kdbx.zip](https://github.com/lxbrvr/alfred-keepassxc-workflow/files/7655121/test.kdbx.zip)

**Comment by lxbrvr** [comment]
Uh, I should have made a more detailed report about some errors to Alfred's debug console. 

@IOIO72 Thank you for the database. I've opened it with no problem and I could search with the workflow. 

The message `"There aren't matches or something went wrong."` tells us there is some problem with the command `/usr/local/bin/keepassxc-cli locate -q <PATH TO KEEPASSXC DATABASE> test`. The example:  `/usr/local/bin/keepassxc-cli locate -q Downloads/test.kdbx test`. After this command you will be asked to enter the master password and if it is valid then the result will be displayed. In your case it's the `/Test` entry.

Please try to run this command on your system. If there are no problems, perform the following steps:

1. remove the workflow from Alfred;
2. download and install the new one - [keepassxc.alfredworkflow.zip](https://github.com/lxbrvr/alfred-keepassxc-workflow/files/7662588/keepassxc.alfredworkflow.zip). I've added the more detailed output;
3. complete the workflow's initialization;
4. try to search something in your database again and show a new output from Alfred's debug console.

**Comment by IOIO72** [comment]
Thank you for the fast response, @lxbrvr  ,

The command line works without any problem.
I still have issues with the Alfred workflow.

Here's the debug output:

```
[21:29:37.855] KeepassXC Alfred[Script Filter] Queuing argument 'Google'
[21:29:38.132] KeepassXC Alfred[Script Filter] Script with argv 'Google' finished
[21:29:38.152] STDERR: KeepassXC Alfred[Script Filter] Traceback (most recent call last):
  File "cli.py", line 45, in main
    parsed_args.handler(parsed_args)
  File "/Users/tamio/Dropbox/Einstellungen/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3AE8EACA-78CE-46E6-BD17-BFCEC045376E/handlers.py", line 44, in wrapper
    return func(*args, **kw)
  File "/Users/tamio/Dropbox/Einstellungen/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3AE8EACA-78CE-46E6-BD17-BFCEC045376E/handlers.py", line 23, in wrapper
    return func(*args, **kw)
  File "/Users/tamio/Dropbox/Einstellungen/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3AE8EACA-78CE-46E6-BD17-BFCEC045376E/handlers.py", line 77, in search_handler
    kp_entries = kp_client.locate(parsed_args.query)
  File "/Users/tamio/Dropbox/Einstellungen/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3AE8EACA-78CE-46E6-BD17-BFCEC045376E/services.py", line 120, in locate
    output = self._run_command(command)
  File "/Users/tamio/Dropbox/Einstellungen/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3AE8EACA-78CE-46E6-BD17-BFCEC045376E/services.py", line 89, in _run_command
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, stdin=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[21:29:38.155] KeepassXC Alfred[Script Filter] {"items": [{"valid": false, "title": "There aren't matches or something went wrong."}]}
```

This is my KeepassXC version:

```
KeePassXC - Version 2.6.6
Revision: 386b79a

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 12.0
CPU-Architektur: x86_64
Kernel: darwin 21.1.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
- libgcrypt 1.9.3
```

My keepass-cli path is the following:
`/Applications/KeePassXC.app/Contents/MacOS/keepassxc-cli`

**Comment by IOIO72** [comment]
@lxbrvr I've changed the path in the workflow settings to `/Applications/KeePassXC.app/Contents/MacOS/keepassxc-cli` and now it works.
Maybe the initialisation script should be aware of this location?

**Comment by IOIO72** [comment]
BTW. Your workflow is fantastic. 🎉  Thanks a lot for your investment! 🥇

**Comment by lxbrvr** [comment]
> I've changed the path in the workflow settings to /Applications/KeePassXC.app/Contents/MacOS/keepassxc-cli and now it works.

I'm glad you were able to make it work!

> Maybe the initialisation script should be aware of this location?

Great idea! Yes, it can be implemented in different ways. I will definitely think about it. 

> BTW. Your workflow is fantastic. 🎉 Thanks a lot for your investment!

Thanks a lot for your feedback!
